### ISSUE TITLE
Enabling "intuition.library" causes analysis to error

### ISSUE THREAD

**Issue by rmtew** [BartmanAbyss/ghidra-amiga#2]
If Intuition library is checked in "Amiga library calls" an error occurs related to RastPort. See next comment.

> (FileDataTypeManager) Data organization upgrade required for Archive 'amiga_ndk39': null

**Comment by rmtew** [comment]
It looks like I can type "R" and change the primary. I'll assume that's correct.

Graphics and other libraries do not seem to be there. Is this correct? What do you do for these?

**Comment by rmtew** [comment]
This error was encountered in the analysis in both the following cases.

1. I had a project being worked on and went to Analysis -> Auto Analyse -> Amiga library calls. Then enabled dos/graphics/intuition/diskfont/exec libraries post-analysis in the analysis settings.
2. I started a new project and reloaded the executable and selected the libraries and then analysed.

```
(These messages are also written to the application log file)

Invalid DataType name: RastPort	*
java.lang.IllegalArgumentException: Invalid DataType name: RastPort	*
	at ghidra.program.model.data.AbstractDataType.<init>(AbstractDataType.java:49)
	at ghidra.program.model.data.DataTypeImpl.<init>(DataTypeImpl.java:54)
	at ghidra.program.model.data.DataTypeImpl.<init>(DataTypeImpl.java:48)
	at ghidra.program.model.data.GenericDataType.<init>(GenericDataType.java:28)
	at ghidra.program.model.data.TypedefDataType.<init>(TypedefDataType.java:64)
	at ghidra.program.model.data.TypedefDataType.<init>(TypedefDataType.java:43)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypes(DataTypeManagerDB.java:2004)
	at amiga.AmigaHunkAnalyzer.getAmigaDataType(AmigaHunkAnalyzer.java:182)
	at amiga.AmigaHunkAnalyzer.createFunctionsSegment(AmigaHunkAnalyzer.java:231)
	at amiga.AmigaHunkAnalyzer.added(AmigaHunkAnalyzer.java:132)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:690)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:790)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:669)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:634)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
