### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by polluks** [BartmanAbyss/ghidra-amiga#6]
```
'void ghidra.app.util.bin.BinaryReader.setPointerIndex(long)'
java.lang.NoSuchMethodError: 'void ghidra.app.util.bin.BinaryReader.setPointerIndex(long)'
	at hunk.HunkBlockFile.peekType(HunkBlockFile.java:59)
	at hunk.HunkBlockFile.isHunkBlockFile(HunkBlockFile.java:15)
	at amiga.AmigaHunkLibFileSystem$AmigaHunkLibFileSystemFactory.probe(AmigaHunkLibFileSystem.java:291)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.test(FileSystemFactoryMgr.java:227)
	at ghidra.formats.gfilesystem.FileSystemService.isFileFilesystemContainer(FileSystemService.java:655)
	at ghidra.plugin.importer.ImporterUtilities.showImportDialog(ImporterUtilities.java:139)
	at ghidra.plugin.importer.ImporterUtilities.lambda$showImportDialog$0(ImporterUtilities.java:106)
	at ghidra.util.task.TaskLauncher$2.run(TaskLauncher.java:117)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0
Java Home: /opt/local/Library/Java/JavaVirtualMachines/openjdk17/Contents/Home
JVM Version: MacPorts 17.0.11
OS: Mac OS X 15.1 aarch64

**Comment by mduggan** [comment]
If you're using the released version this is caused by a version mismatch with the latest Ghidra (11.x).  The simple fix is to rebuild the extension from source - no code change is needed. Check it out and run:
```
$ gradle -PGHIDRA_INSTALL_DIR=/full/path/to/your/ghidra/install
```
